# Generated by Django 5.0.2 on 2024-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='nombre clabe')),
                ('name', models.CharField(max_length=100, verbose_name='Red social')),
                ('url', models.URLField(blank=True, max_length=120, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['name'],
            },
        ),
    ]
